# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TechnewsTui < Formula
  desc "A terminal UI for Hacker News and Reddit"
  homepage "https://github.com/joeyism/technews-tui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeyism/technews-tui/releases/download/v0.2.0/technews-tui_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "4a7a6cccbcaa463f15381f877b9b31ac4385f0193dd7b877ccac7822f04e3967"

      define_method(:install) do
        bin.install "technews-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeyism/technews-tui/releases/download/v0.2.0/technews-tui_0.2.0_Darwin_arm64.tar.gz"
      sha256 "98c6124a29f544f8bf6f01fb79d0b3f0edd80ed6941e6e9c8e0bc27c04d4d9e8"

      define_method(:install) do
        bin.install "technews-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeyism/technews-tui/releases/download/v0.2.0/technews-tui_0.2.0_Linux_x86_64.tar.gz"
      sha256 "4710b9cf495467d9bfdbc704316beb9ccd46b88e2af8161752f9e094a4acdeea"
      define_method(:install) do
        bin.install "technews-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeyism/technews-tui/releases/download/v0.2.0/technews-tui_0.2.0_Linux_arm64.tar.gz"
      sha256 "35c47f8cd161aa5f83ae5c7f5959280290366b91484bc9dd9f0ff9f874d39297"
      define_method(:install) do
        bin.install "technews-tui"
      end
    end
  end
end
